list: $/sepehr/crm/models/forwardstatus/columns.yaml
modelClass: Sepehr\Crm\Models\ForwardStatus
title: ForwardStatusController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sepehr/crm/forwardstatuscontroller/update/:id'
