list: $/sepehr/crm/models/servicestatus/columns.yaml
modelClass: Sepehr\Crm\Models\ServiceStatus
title: ServiceStatusController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sepehr/crm/servicestatuscontroller/update/:id'
